// <auto-generated />
using System;
using EVS.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVS.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240311112837_RidesSeed2")]
    partial class RidesSeed2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EVS.Core.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comments");

                    b.Property<int>("Note")
                        .HasColumnType("int")
                        .HasColumnName("note");

                    b.Property<Guid>("RideId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ride_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.HasIndex("UserId");

                    b.ToTable("feedback");
                });

            modelBuilder.Entity("EVS.Core.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("reservation_date");

                    b.Property<Guid>("RideId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ride_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.HasIndex("UserId");

                    b.ToTable("reservation");
                });

            modelBuilder.Entity("EVS.Core.Models.Ride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2")
                        .HasColumnName("departure");

                    b.Property<int>("Distance")
                        .HasColumnType("int")
                        .HasColumnName("distance");

                    b.Property<string>("EndCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("end_city");

                    b.Property<double>("EndLatitude")
                        .HasColumnType("float")
                        .HasColumnName("end_latitude");

                    b.Property<double>("EndLongitude")
                        .HasColumnType("float")
                        .HasColumnName("end_longitude");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<int>("Seats")
                        .HasColumnType("int")
                        .HasColumnName("seats");

                    b.Property<string>("StartCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("start_city");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("float")
                        .HasColumnName("start_latitude");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("float")
                        .HasColumnName("start_longitude");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ride");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d76d087-f7c7-4ed6-be1a-4f7f48d977f7"),
                            Departure = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Distance = 204,
                            EndCity = "Paris, France",
                            EndLatitude = 48.858825500000002,
                            EndLongitude = 2.2646343999999998,
                            Price = 20.0,
                            Seats = 3,
                            StartCity = "Lille, France",
                            StartLatitude = 50.631073299999997,
                            StartLongitude = 3.0056983000000002,
                            UserId = new Guid("91dc47be-9d2b-4d64-b1a0-bc299c2eb87a")
                        },
                        new
                        {
                            Id = new Guid("1e830ccd-86d5-450f-b970-8ac91f66f389"),
                            Departure = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Distance = 204,
                            EndCity = "Paris, France",
                            EndLatitude = 48.858825500000002,
                            EndLongitude = 2.2646343999999998,
                            Price = 18.0,
                            Seats = 2,
                            StartCity = "Lille, France",
                            StartLatitude = 50.631073299999997,
                            StartLongitude = 3.0056983000000002,
                            UserId = new Guid("063983f2-60ec-4900-af2c-a47845f5edf4")
                        },
                        new
                        {
                            Id = new Guid("54637b0b-e4c0-4d50-9a15-11c73b2a182b"),
                            Departure = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Distance = 204,
                            EndCity = "Lille, France",
                            EndLatitude = 50.631073299999997,
                            EndLongitude = 3.0056983000000002,
                            Price = 23.0,
                            Seats = 4,
                            StartCity = "Paris, France",
                            StartLatitude = 48.858825500000002,
                            StartLongitude = 2.2646343999999998,
                            UserId = new Guid("9e1727ce-2538-4690-aaa0-5918e3149141")
                        });
                });

            modelBuilder.Entity("EVS.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Birthday")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("birthday");

                    b.Property<string>("CarDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("car_description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("photo");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("pseudo");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Pseudo")
                        .IsUnique();

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44a0b880-33bf-45be-a930-a4f105d75aa1"),
                            Birthday = new DateTime(2024, 3, 11, 12, 28, 37, 621, DateTimeKind.Local).AddTicks(7331),
                            CarDescription = "",
                            Email = "admin@envoituresimone.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            Password = "admin",
                            PhoneNumber = "0102030405",
                            Photo = "",
                            Pseudo = "admin"
                        },
                        new
                        {
                            Id = new Guid("91dc47be-9d2b-4d64-b1a0-bc299c2eb87a"),
                            Birthday = new DateTime(1998, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Daewoo",
                            Email = "naldren0@webeden.co.uk",
                            FirstName = "Amye",
                            LastName = "Colchett",
                            Password = "aB0.oB?iBy\\",
                            PhoneNumber = "0337862430",
                            Photo = "",
                            Pseudo = "acolchett0"
                        },
                        new
                        {
                            Id = new Guid("9e1727ce-2538-4690-aaa0-5918e3149141"),
                            Birthday = new DateTime(1974, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Lexus",
                            Email = "ddroogan1@thetimes.co.uk",
                            FirstName = "Nap",
                            LastName = "Droogan",
                            Password = "tH0)I/Mt<xZwz2",
                            PhoneNumber = "0322458382",
                            Photo = "",
                            Pseudo = "ddroogan1"
                        },
                        new
                        {
                            Id = new Guid("063983f2-60ec-4900-af2c-a47845f5edf4"),
                            Birthday = new DateTime(1988, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Jeep",
                            Email = "kpedwell2@icq.com",
                            FirstName = "Kordula",
                            LastName = "Pedwell",
                            Password = "pH3+&{WpvdT",
                            PhoneNumber = "0903434966",
                            Photo = "",
                            Pseudo = "kpedwell2"
                        },
                        new
                        {
                            Id = new Guid("7005279b-f7ec-4e30-a94a-d5e155059d6e"),
                            Birthday = new DateTime(1984, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Austin",
                            Email = "lhair3@wikipedia.org",
                            FirstName = "Lindsey",
                            LastName = "Hair",
                            Password = "eE0'6STA~9O#Suj{",
                            PhoneNumber = "0162842195",
                            Photo = "",
                            Pseudo = "lhair3"
                        },
                        new
                        {
                            Id = new Guid("b2ec9189-fdcb-4fd9-b56e-c41c54cdbe4b"),
                            Birthday = new DateTime(1997, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "BMW",
                            Email = "cgrigorkin4@theatlantic.com",
                            FirstName = "Carlota",
                            LastName = "Grigorkin",
                            Password = "tZ9\\4s(DQvnvE",
                            PhoneNumber = "0494223557",
                            Photo = "",
                            Pseudo = "cgrigorkin4"
                        });
                });

            modelBuilder.Entity("EVS.Core.Models.Feedback", b =>
                {
                    b.HasOne("EVS.Core.Models.Ride", "Ride")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVS.Core.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVS.Core.Models.Reservation", b =>
                {
                    b.HasOne("EVS.Core.Models.Ride", "Ride")
                        .WithMany("Reservations")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVS.Core.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVS.Core.Models.Ride", b =>
                {
                    b.HasOne("EVS.Core.Models.User", "User")
                        .WithMany("Rides")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVS.Core.Models.Ride", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("EVS.Core.Models.User", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Reservations");

                    b.Navigation("Rides");
                });
#pragma warning restore 612, 618
        }
    }
}
