// <auto-generated />
using System;
using EVS.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVS.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240311141723_RideHours")]
    partial class RideHours
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EVS.Core.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comments");

                    b.Property<int>("Note")
                        .HasColumnType("int")
                        .HasColumnName("note");

                    b.Property<Guid>("RideId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ride_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.HasIndex("UserId");

                    b.ToTable("feedback");

                    b.HasData(
                        new
                        {
                            Id = new Guid("214e5f7f-482b-44b3-9fd3-94d8d21dced3"),
                            Comments = "J'ai pris un EVS à cause de la grève sncf. Au bout de dix minutes de discussion, il y a un passager qui dit \"Eh ca vous dis pas un covoiturage où tout le monde ferme sa gueule ?\"\r\nGrand silence depuis, plus personne ose parler.",
                            Note = 4,
                            RideId = new Guid("67a94c3d-f0d2-483a-ac9b-d140c5d28cd8"),
                            UserId = new Guid("7db3addc-9bc1-4b11-96e8-c6863c4dfb7b")
                        },
                        new
                        {
                            Id = new Guid("69ec4c86-8d1d-45c7-87f4-35f96c3480e1"),
                            Comments = "En Voiture Simone qui m'envoie une notif pour me dire que je suis éligible à la prime de l'Etat de 100€ pour encourager le convoiturage mdrrr ok il me manque juste le permis mais sinon ok je suis éligible 😭",
                            Note = 5,
                            RideId = new Guid("67a94c3d-f0d2-483a-ac9b-d140c5d28cd8"),
                            UserId = new Guid("3ed49088-8824-47c8-9005-5f7526e92099")
                        },
                        new
                        {
                            Id = new Guid("935d27c5-0a28-4b8d-bcb8-a90b4d56ccdc"),
                            Comments = "suis dans mon EVS il a fermé les fenetres j’ose pas dire que j’ai des cheveux coincés dedans je peux pas bouger omg",
                            Note = 3,
                            RideId = new Guid("67a94c3d-f0d2-483a-ac9b-d140c5d28cd8"),
                            UserId = new Guid("1a284bf2-84bd-48da-89b4-ceaff5540001")
                        });
                });

            modelBuilder.Entity("EVS.Core.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("reservation_date");

                    b.Property<Guid>("RideId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ride_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.HasIndex("UserId");

                    b.ToTable("reservation");

                    b.HasData(
                        new
                        {
                            Id = new Guid("579f0bfa-f54c-42da-92c5-84c18654392a"),
                            ReservationDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            RideId = new Guid("fd77fe65-b625-4a38-bdac-da1735c726c7"),
                            Status = 1,
                            UserId = new Guid("1a284bf2-84bd-48da-89b4-ceaff5540001")
                        },
                        new
                        {
                            Id = new Guid("32cc63f8-d43f-49c2-b72e-263bb5ebc379"),
                            ReservationDate = new DateTime(2024, 3, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            RideId = new Guid("b75690bc-d5bd-4b8f-923d-5c434355b34f"),
                            Status = 2,
                            UserId = new Guid("76b74fd2-186a-4fc2-a4e3-00995f5adb4a")
                        },
                        new
                        {
                            Id = new Guid("6211ca80-cdc4-4bf5-b67a-3c9ea0bd3540"),
                            ReservationDate = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            RideId = new Guid("fd77fe65-b625-4a38-bdac-da1735c726c7"),
                            Status = 1,
                            UserId = new Guid("9b2e221b-c01a-405d-84b5-5f38fbe956b2")
                        });
                });

            modelBuilder.Entity("EVS.Core.Models.Ride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2")
                        .HasColumnName("departure");

                    b.Property<int>("Distance")
                        .HasColumnType("int")
                        .HasColumnName("distance");

                    b.Property<string>("EndCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("end_city");

                    b.Property<double>("EndLatitude")
                        .HasColumnType("float")
                        .HasColumnName("end_latitude");

                    b.Property<double>("EndLongitude")
                        .HasColumnType("float")
                        .HasColumnName("end_longitude");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<int>("Seats")
                        .HasColumnType("int")
                        .HasColumnName("seats");

                    b.Property<string>("StartCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("start_city");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("float")
                        .HasColumnName("start_latitude");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("float")
                        .HasColumnName("start_longitude");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ride");

                    b.HasData(
                        new
                        {
                            Id = new Guid("906a4c29-eccf-4f68-abb4-65a3d1307662"),
                            Departure = new DateTime(2024, 3, 16, 7, 0, 0, 0, DateTimeKind.Local),
                            Distance = 204,
                            EndCity = "Paris",
                            EndLatitude = 48.858825500000002,
                            EndLongitude = 2.2646343999999998,
                            Price = 20.0,
                            Seats = 3,
                            StartCity = "Lille",
                            StartLatitude = 50.631073299999997,
                            StartLongitude = 3.0056983000000002,
                            UserId = new Guid("7db3addc-9bc1-4b11-96e8-c6863c4dfb7b")
                        },
                        new
                        {
                            Id = new Guid("fd77fe65-b625-4a38-bdac-da1735c726c7"),
                            Departure = new DateTime(2024, 3, 17, 11, 0, 0, 0, DateTimeKind.Local),
                            Distance = 204,
                            EndCity = "Paris",
                            EndLatitude = 48.858825500000002,
                            EndLongitude = 2.2646343999999998,
                            Price = 18.0,
                            Seats = 2,
                            StartCity = "Lille",
                            StartLatitude = 50.631073299999997,
                            StartLongitude = 3.0056983000000002,
                            UserId = new Guid("9b2e221b-c01a-405d-84b5-5f38fbe956b2")
                        },
                        new
                        {
                            Id = new Guid("b75690bc-d5bd-4b8f-923d-5c434355b34f"),
                            Departure = new DateTime(2024, 3, 21, 17, 0, 0, 0, DateTimeKind.Local),
                            Distance = 204,
                            EndCity = "Lille",
                            EndLatitude = 50.631073299999997,
                            EndLongitude = 3.0056983000000002,
                            Price = 23.0,
                            Seats = 4,
                            StartCity = "Paris",
                            StartLatitude = 48.858825500000002,
                            StartLongitude = 2.2646343999999998,
                            UserId = new Guid("3ed49088-8824-47c8-9005-5f7526e92099")
                        },
                        new
                        {
                            Id = new Guid("3996f952-72ba-46c3-9818-beee4257f3a1"),
                            Departure = new DateTime(2024, 3, 28, 5, 0, 0, 0, DateTimeKind.Local),
                            Distance = 660,
                            EndCity = "Marseille",
                            EndLatitude = 43.280226999999996,
                            EndLongitude = 5.2158397000000001,
                            Price = 39.0,
                            Seats = 1,
                            StartCity = "Paris",
                            StartLatitude = 48.858825500000002,
                            StartLongitude = 2.2646343999999998,
                            UserId = new Guid("76b74fd2-186a-4fc2-a4e3-00995f5adb4a")
                        },
                        new
                        {
                            Id = new Guid("97bf8059-5dd3-47aa-b4b2-122030dd08fd"),
                            Departure = new DateTime(2024, 3, 20, 4, 0, 0, 0, DateTimeKind.Local),
                            Distance = 435,
                            EndCity = "Bordeaux",
                            EndLatitude = 44.841225000000001,
                            EndLongitude = -0.580036,
                            Price = 46.0,
                            Seats = 3,
                            StartCity = "Lyon",
                            StartLatitude = 45.757814000000003,
                            StartLongitude = 4.8320109999999996,
                            UserId = new Guid("76b74fd2-186a-4fc2-a4e3-00995f5adb4a")
                        },
                        new
                        {
                            Id = new Guid("67a94c3d-f0d2-483a-ac9b-d140c5d28cd8"),
                            Departure = new DateTime(2024, 3, 7, 8, 0, 0, 0, DateTimeKind.Local),
                            Distance = 699,
                            EndCity = "Lille",
                            EndLatitude = 50.631073299999997,
                            EndLongitude = 50.631073299999997,
                            Price = 52.0,
                            Seats = 2,
                            StartCity = "Bordeaux",
                            StartLatitude = 44.841225000000001,
                            StartLongitude = -0.580036,
                            UserId = new Guid("76b74fd2-186a-4fc2-a4e3-00995f5adb4a")
                        });
                });

            modelBuilder.Entity("EVS.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Birthday")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("birthday");

                    b.Property<string>("CarDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("car_description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("photo");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("pseudo");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Pseudo")
                        .IsUnique();

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ecfb3f3-cbd1-4645-a9c4-786545285bec"),
                            Birthday = new DateTime(2024, 3, 11, 15, 17, 23, 206, DateTimeKind.Local).AddTicks(3130),
                            CarDescription = "",
                            Email = "admin@envoituresimone.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            Password = "admin",
                            PhoneNumber = "0102030405",
                            Photo = "https://thispersondoesnotexist.com/",
                            Pseudo = "admin"
                        },
                        new
                        {
                            Id = new Guid("7db3addc-9bc1-4b11-96e8-c6863c4dfb7b"),
                            Birthday = new DateTime(1998, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Daewoo",
                            Email = "naldren0@webeden.co.uk",
                            FirstName = "Amye",
                            LastName = "Colchett",
                            Password = "aB0.oB?iBy\\",
                            PhoneNumber = "0337862430",
                            Photo = "https://thispersondoesnotexist.com/",
                            Pseudo = "acolchett0"
                        },
                        new
                        {
                            Id = new Guid("3ed49088-8824-47c8-9005-5f7526e92099"),
                            Birthday = new DateTime(1974, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Lexus",
                            Email = "ddroogan1@thetimes.co.uk",
                            FirstName = "Nap",
                            LastName = "Droogan",
                            Password = "tH0)I/Mt<xZwz2",
                            PhoneNumber = "0322458382",
                            Photo = "https://thispersondoesnotexist.com/",
                            Pseudo = "ddroogan1"
                        },
                        new
                        {
                            Id = new Guid("9b2e221b-c01a-405d-84b5-5f38fbe956b2"),
                            Birthday = new DateTime(1988, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Jeep",
                            Email = "kpedwell2@icq.com",
                            FirstName = "Kordula",
                            LastName = "Pedwell",
                            Password = "pH3+&{WpvdT",
                            PhoneNumber = "0903434966",
                            Photo = "https://thispersondoesnotexist.com/",
                            Pseudo = "kpedwell2"
                        },
                        new
                        {
                            Id = new Guid("1a284bf2-84bd-48da-89b4-ceaff5540001"),
                            Birthday = new DateTime(1984, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Austin",
                            Email = "lhair3@wikipedia.org",
                            FirstName = "Lindsey",
                            LastName = "Hair",
                            Password = "eE0'6STA~9O#Suj{",
                            PhoneNumber = "0162842195",
                            Photo = "https://thispersondoesnotexist.com/",
                            Pseudo = "lhair3"
                        },
                        new
                        {
                            Id = new Guid("76b74fd2-186a-4fc2-a4e3-00995f5adb4a"),
                            Birthday = new DateTime(1997, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "BMW",
                            Email = "cgrigorkin4@theatlantic.com",
                            FirstName = "Carlota",
                            LastName = "Grigorkin",
                            Password = "tZ9\\4s(DQvnvE",
                            PhoneNumber = "0494223557",
                            Photo = "https://thispersondoesnotexist.com/",
                            Pseudo = "cgrigorkin4"
                        });
                });

            modelBuilder.Entity("EVS.Core.Models.Feedback", b =>
                {
                    b.HasOne("EVS.Core.Models.Ride", "Ride")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVS.Core.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVS.Core.Models.Reservation", b =>
                {
                    b.HasOne("EVS.Core.Models.Ride", "Ride")
                        .WithMany("Reservations")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVS.Core.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVS.Core.Models.Ride", b =>
                {
                    b.HasOne("EVS.Core.Models.User", "User")
                        .WithMany("Rides")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVS.Core.Models.Ride", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("EVS.Core.Models.User", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Reservations");

                    b.Navigation("Rides");
                });
#pragma warning restore 612, 618
        }
    }
}
