// <auto-generated />
using System;
using EVS.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVS.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240311124915_ReservationsSeed")]
    partial class ReservationsSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EVS.Core.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comments");

                    b.Property<int>("Note")
                        .HasColumnType("int")
                        .HasColumnName("note");

                    b.Property<Guid>("RideId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ride_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.HasIndex("UserId");

                    b.ToTable("feedback");
                });

            modelBuilder.Entity("EVS.Core.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("reservation_date");

                    b.Property<Guid>("RideId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ride_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.HasIndex("UserId");

                    b.ToTable("reservation");

                    b.HasData(
                        new
                        {
                            Id = new Guid("645d7f57-ef9c-467a-b431-89be2d5907b2"),
                            ReservationDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            RideId = new Guid("0c3dfda0-1d21-479e-a95a-df4ec7762751"),
                            Status = 1,
                            UserId = new Guid("b9cfbd1d-f40c-447d-8270-1a7b3c64ca45")
                        },
                        new
                        {
                            Id = new Guid("8b12721f-042e-4436-ad57-f8ac7f9b7c55"),
                            ReservationDate = new DateTime(2024, 3, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            RideId = new Guid("0c3dfda0-1d21-479e-a95a-df4ec7762751"),
                            Status = 2,
                            UserId = new Guid("7b456ebb-0cb0-4a3f-8262-4a48cddee710")
                        },
                        new
                        {
                            Id = new Guid("8c7e1005-1612-49da-9f37-34197f6609fa"),
                            ReservationDate = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            RideId = new Guid("0c3dfda0-1d21-479e-a95a-df4ec7762751"),
                            Status = 1,
                            UserId = new Guid("7b456ebb-0cb0-4a3f-8262-4a48cddee710")
                        });
                });

            modelBuilder.Entity("EVS.Core.Models.Ride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2")
                        .HasColumnName("departure");

                    b.Property<int>("Distance")
                        .HasColumnType("int")
                        .HasColumnName("distance");

                    b.Property<string>("EndCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("end_city");

                    b.Property<double>("EndLatitude")
                        .HasColumnType("float")
                        .HasColumnName("end_latitude");

                    b.Property<double>("EndLongitude")
                        .HasColumnType("float")
                        .HasColumnName("end_longitude");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<int>("Seats")
                        .HasColumnType("int")
                        .HasColumnName("seats");

                    b.Property<string>("StartCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("start_city");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("float")
                        .HasColumnName("start_latitude");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("float")
                        .HasColumnName("start_longitude");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ride");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72580adb-0b5c-4c6d-a6b8-86e3900e418d"),
                            Departure = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Distance = 204,
                            EndCity = "Paris, France",
                            EndLatitude = 48.858825500000002,
                            EndLongitude = 2.2646343999999998,
                            Price = 20.0,
                            Seats = 3,
                            StartCity = "Lille, France",
                            StartLatitude = 50.631073299999997,
                            StartLongitude = 3.0056983000000002,
                            UserId = new Guid("a935d881-1d6e-4c0b-a36d-26b4ae371e7f")
                        },
                        new
                        {
                            Id = new Guid("59ebc358-4602-4a7e-ac4a-8eeaabebadf7"),
                            Departure = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Distance = 204,
                            EndCity = "Paris, France",
                            EndLatitude = 48.858825500000002,
                            EndLongitude = 2.2646343999999998,
                            Price = 18.0,
                            Seats = 2,
                            StartCity = "Lille, France",
                            StartLatitude = 50.631073299999997,
                            StartLongitude = 3.0056983000000002,
                            UserId = new Guid("a9fa0a54-8e2c-46d4-a457-9c51367ddfca")
                        },
                        new
                        {
                            Id = new Guid("68c98202-5674-4d3a-bb9e-3fe11807ebfc"),
                            Departure = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Distance = 204,
                            EndCity = "Lille, France",
                            EndLatitude = 50.631073299999997,
                            EndLongitude = 3.0056983000000002,
                            Price = 23.0,
                            Seats = 4,
                            StartCity = "Paris, France",
                            StartLatitude = 48.858825500000002,
                            StartLongitude = 2.2646343999999998,
                            UserId = new Guid("51879bb5-18cc-4aeb-b2ce-7ff92b4bd1ba")
                        },
                        new
                        {
                            Id = new Guid("bad0b23c-da84-4cd8-a18f-7ffd5d77df67"),
                            Departure = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Distance = 660,
                            EndCity = "Marseille, France",
                            EndLatitude = 43.280226999999996,
                            EndLongitude = 5.2158397000000001,
                            Price = 39.0,
                            Seats = 1,
                            StartCity = "Paris, France",
                            StartLatitude = 48.858825500000002,
                            StartLongitude = 2.2646343999999998,
                            UserId = new Guid("7b456ebb-0cb0-4a3f-8262-4a48cddee710")
                        },
                        new
                        {
                            Id = new Guid("6e408262-db26-49a6-addd-ca06744955ba"),
                            Departure = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Distance = 435,
                            EndCity = "Bordeaux, France",
                            EndLatitude = 44.841225000000001,
                            EndLongitude = -0.580036,
                            Price = 46.0,
                            Seats = 3,
                            StartCity = "Lyon, France",
                            StartLatitude = 45.757814000000003,
                            StartLongitude = 4.8320109999999996,
                            UserId = new Guid("7b456ebb-0cb0-4a3f-8262-4a48cddee710")
                        },
                        new
                        {
                            Id = new Guid("0c3dfda0-1d21-479e-a95a-df4ec7762751"),
                            Departure = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Distance = 699,
                            EndCity = "Lille, France",
                            EndLatitude = 50.631073299999997,
                            EndLongitude = 50.631073299999997,
                            Price = 52.0,
                            Seats = 2,
                            StartCity = "Bordeaux, France",
                            StartLatitude = 44.841225000000001,
                            StartLongitude = -0.580036,
                            UserId = new Guid("7b456ebb-0cb0-4a3f-8262-4a48cddee710")
                        });
                });

            modelBuilder.Entity("EVS.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Birthday")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("birthday");

                    b.Property<string>("CarDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("car_description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("photo");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("pseudo");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Pseudo")
                        .IsUnique();

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58eef135-100d-45da-9cbc-dabe6288f162"),
                            Birthday = new DateTime(2024, 3, 11, 13, 49, 14, 714, DateTimeKind.Local).AddTicks(9156),
                            CarDescription = "",
                            Email = "admin@envoituresimone.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            Password = "admin",
                            PhoneNumber = "0102030405",
                            Photo = "",
                            Pseudo = "admin"
                        },
                        new
                        {
                            Id = new Guid("a935d881-1d6e-4c0b-a36d-26b4ae371e7f"),
                            Birthday = new DateTime(1998, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Daewoo",
                            Email = "naldren0@webeden.co.uk",
                            FirstName = "Amye",
                            LastName = "Colchett",
                            Password = "aB0.oB?iBy\\",
                            PhoneNumber = "0337862430",
                            Photo = "",
                            Pseudo = "acolchett0"
                        },
                        new
                        {
                            Id = new Guid("51879bb5-18cc-4aeb-b2ce-7ff92b4bd1ba"),
                            Birthday = new DateTime(1974, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Lexus",
                            Email = "ddroogan1@thetimes.co.uk",
                            FirstName = "Nap",
                            LastName = "Droogan",
                            Password = "tH0)I/Mt<xZwz2",
                            PhoneNumber = "0322458382",
                            Photo = "",
                            Pseudo = "ddroogan1"
                        },
                        new
                        {
                            Id = new Guid("a9fa0a54-8e2c-46d4-a457-9c51367ddfca"),
                            Birthday = new DateTime(1988, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Jeep",
                            Email = "kpedwell2@icq.com",
                            FirstName = "Kordula",
                            LastName = "Pedwell",
                            Password = "pH3+&{WpvdT",
                            PhoneNumber = "0903434966",
                            Photo = "",
                            Pseudo = "kpedwell2"
                        },
                        new
                        {
                            Id = new Guid("b9cfbd1d-f40c-447d-8270-1a7b3c64ca45"),
                            Birthday = new DateTime(1984, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Austin",
                            Email = "lhair3@wikipedia.org",
                            FirstName = "Lindsey",
                            LastName = "Hair",
                            Password = "eE0'6STA~9O#Suj{",
                            PhoneNumber = "0162842195",
                            Photo = "",
                            Pseudo = "lhair3"
                        },
                        new
                        {
                            Id = new Guid("7b456ebb-0cb0-4a3f-8262-4a48cddee710"),
                            Birthday = new DateTime(1997, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "BMW",
                            Email = "cgrigorkin4@theatlantic.com",
                            FirstName = "Carlota",
                            LastName = "Grigorkin",
                            Password = "tZ9\\4s(DQvnvE",
                            PhoneNumber = "0494223557",
                            Photo = "",
                            Pseudo = "cgrigorkin4"
                        });
                });

            modelBuilder.Entity("EVS.Core.Models.Feedback", b =>
                {
                    b.HasOne("EVS.Core.Models.Ride", "Ride")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVS.Core.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVS.Core.Models.Reservation", b =>
                {
                    b.HasOne("EVS.Core.Models.Ride", "Ride")
                        .WithMany("Reservations")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVS.Core.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVS.Core.Models.Ride", b =>
                {
                    b.HasOne("EVS.Core.Models.User", "User")
                        .WithMany("Rides")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVS.Core.Models.Ride", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("EVS.Core.Models.User", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Reservations");

                    b.Navigation("Rides");
                });
#pragma warning restore 612, 618
        }
    }
}
