// <auto-generated />
using System;
using EVS.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVS.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EVS.Core.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comments");

                    b.Property<int>("Note")
                        .HasColumnType("int")
                        .HasColumnName("note");

                    b.Property<Guid>("RideId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ride_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.HasIndex("UserId");

                    b.ToTable("feedback");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ceb2dd01-4944-44d3-b4db-99a4b6fb032d"),
                            Comments = "J'ai pris un EVS à cause de la grève sncf. Au bout de dix minutes de discussion, il y a un passager qui dit \"Eh ca vous dis pas un covoiturage où tout le monde ferme sa gueule ?\"\r\nGrand silence depuis, plus personne ose parler.",
                            Note = 4,
                            RideId = new Guid("3742a581-a8a9-4dca-b95e-8f1b9391e436"),
                            UserId = new Guid("8b2d4c69-f3d5-4d00-b02b-103bd26dd550")
                        },
                        new
                        {
                            Id = new Guid("799c85fa-a3ec-4ee5-8e2c-fec660893ba7"),
                            Comments = "En Voiture Simone qui m'envoie une notif pour me dire que je suis éligible à la prime de l'Etat de 100€ pour encourager le convoiturage mdrrr ok il me manque juste le permis mais sinon ok je suis éligible 😭",
                            Note = 5,
                            RideId = new Guid("3742a581-a8a9-4dca-b95e-8f1b9391e436"),
                            UserId = new Guid("b897d47e-7b3b-4dc0-a028-05d8e2c69659")
                        },
                        new
                        {
                            Id = new Guid("44e9f84d-5933-481e-97fe-15e1b967855e"),
                            Comments = "suis dans mon EVS il a fermé les fenetres j’ose pas dire que j’ai des cheveux coincés dedans je peux pas bouger omg",
                            Note = 3,
                            RideId = new Guid("3742a581-a8a9-4dca-b95e-8f1b9391e436"),
                            UserId = new Guid("485e4e29-6217-415c-b438-3d4f114f24d6")
                        });
                });

            modelBuilder.Entity("EVS.Core.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("reservation_date");

                    b.Property<Guid>("RideId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ride_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.HasIndex("UserId");

                    b.ToTable("reservation");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bea20ab2-b7d9-46d4-bfb7-611035e3ae82"),
                            ReservationDate = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            RideId = new Guid("57ab4f5a-31e4-44a4-bd92-b664136b65be"),
                            Status = 1,
                            UserId = new Guid("485e4e29-6217-415c-b438-3d4f114f24d6")
                        },
                        new
                        {
                            Id = new Guid("804dd9b0-0361-4a40-880a-5d6c5f2e1364"),
                            ReservationDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            RideId = new Guid("7d712d7e-f6f8-47b7-9176-8145b4480159"),
                            Status = 2,
                            UserId = new Guid("24c952e2-dd86-4ca5-9308-771f2ab597fd")
                        },
                        new
                        {
                            Id = new Guid("ad65bde4-5b18-4dbc-bd85-2c09b669ab8b"),
                            ReservationDate = new DateTime(2024, 3, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            RideId = new Guid("57ab4f5a-31e4-44a4-bd92-b664136b65be"),
                            Status = 1,
                            UserId = new Guid("2c08f978-5efd-4471-b487-6df11f5ebd37")
                        });
                });

            modelBuilder.Entity("EVS.Core.Models.Ride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2")
                        .HasColumnName("departure");

                    b.Property<int>("Distance")
                        .HasColumnType("int")
                        .HasColumnName("distance");

                    b.Property<string>("EndCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("end_city");

                    b.Property<double>("EndLatitude")
                        .HasColumnType("float")
                        .HasColumnName("end_latitude");

                    b.Property<double>("EndLongitude")
                        .HasColumnType("float")
                        .HasColumnName("end_longitude");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<int>("Seats")
                        .HasColumnType("int")
                        .HasColumnName("seats");

                    b.Property<string>("StartCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("start_city");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("float")
                        .HasColumnName("start_latitude");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("float")
                        .HasColumnName("start_longitude");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ride");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2810f5bb-cddf-4f72-854d-4b84a2cf8e02"),
                            Departure = new DateTime(2024, 3, 17, 7, 0, 0, 0, DateTimeKind.Local),
                            Distance = 204,
                            EndCity = "Paris",
                            EndLatitude = 48.858825500000002,
                            EndLongitude = 2.2646343999999998,
                            Price = 20.0,
                            Seats = 3,
                            StartCity = "Lille",
                            StartLatitude = 50.631073299999997,
                            StartLongitude = 3.0056983000000002,
                            UserId = new Guid("8b2d4c69-f3d5-4d00-b02b-103bd26dd550")
                        },
                        new
                        {
                            Id = new Guid("57ab4f5a-31e4-44a4-bd92-b664136b65be"),
                            Departure = new DateTime(2024, 3, 18, 11, 0, 0, 0, DateTimeKind.Local),
                            Distance = 204,
                            EndCity = "Paris",
                            EndLatitude = 48.858825500000002,
                            EndLongitude = 2.2646343999999998,
                            Price = 18.0,
                            Seats = 2,
                            StartCity = "Lille",
                            StartLatitude = 50.631073299999997,
                            StartLongitude = 3.0056983000000002,
                            UserId = new Guid("2c08f978-5efd-4471-b487-6df11f5ebd37")
                        },
                        new
                        {
                            Id = new Guid("7d712d7e-f6f8-47b7-9176-8145b4480159"),
                            Departure = new DateTime(2024, 3, 22, 17, 0, 0, 0, DateTimeKind.Local),
                            Distance = 204,
                            EndCity = "Lille",
                            EndLatitude = 50.631073299999997,
                            EndLongitude = 3.0056983000000002,
                            Price = 23.0,
                            Seats = 4,
                            StartCity = "Paris",
                            StartLatitude = 48.858825500000002,
                            StartLongitude = 2.2646343999999998,
                            UserId = new Guid("b897d47e-7b3b-4dc0-a028-05d8e2c69659")
                        },
                        new
                        {
                            Id = new Guid("4fd3c98e-f891-44be-a932-8b8ab1f07c72"),
                            Departure = new DateTime(2024, 3, 29, 5, 0, 0, 0, DateTimeKind.Local),
                            Distance = 660,
                            EndCity = "Marseille",
                            EndLatitude = 43.280226999999996,
                            EndLongitude = 5.2158397000000001,
                            Price = 39.0,
                            Seats = 1,
                            StartCity = "Paris",
                            StartLatitude = 48.858825500000002,
                            StartLongitude = 2.2646343999999998,
                            UserId = new Guid("24c952e2-dd86-4ca5-9308-771f2ab597fd")
                        },
                        new
                        {
                            Id = new Guid("19c699fd-f005-415f-b655-3e8edc9fa9e4"),
                            Departure = new DateTime(2024, 3, 21, 4, 0, 0, 0, DateTimeKind.Local),
                            Distance = 435,
                            EndCity = "Bordeaux",
                            EndLatitude = 44.841225000000001,
                            EndLongitude = -0.580036,
                            Price = 46.0,
                            Seats = 3,
                            StartCity = "Lyon",
                            StartLatitude = 45.757814000000003,
                            StartLongitude = 4.8320109999999996,
                            UserId = new Guid("24c952e2-dd86-4ca5-9308-771f2ab597fd")
                        },
                        new
                        {
                            Id = new Guid("3742a581-a8a9-4dca-b95e-8f1b9391e436"),
                            Departure = new DateTime(2024, 3, 8, 8, 0, 0, 0, DateTimeKind.Local),
                            Distance = 699,
                            EndCity = "Lille",
                            EndLatitude = 50.631073299999997,
                            EndLongitude = 50.631073299999997,
                            Price = 52.0,
                            Seats = 2,
                            StartCity = "Bordeaux",
                            StartLatitude = 44.841225000000001,
                            StartLongitude = -0.580036,
                            UserId = new Guid("24c952e2-dd86-4ca5-9308-771f2ab597fd")
                        });
                });

            modelBuilder.Entity("EVS.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("AcceptFood")
                        .HasColumnType("bit")
                        .HasColumnName("accept_food");

                    b.Property<bool>("AcceptMusic")
                        .HasColumnType("bit")
                        .HasColumnName("accept_music");

                    b.Property<bool>("AcceptPet")
                        .HasColumnType("bit")
                        .HasColumnName("accept_pet");

                    b.Property<bool>("AcceptSmallTalk")
                        .HasColumnType("bit")
                        .HasColumnName("accept_talk");

                    b.Property<bool>("AcceptSmoker")
                        .HasColumnType("bit")
                        .HasColumnName("accept_smoker");

                    b.Property<DateTime?>("Birthday")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("birthday");

                    b.Property<string>("CarDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("car_description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_admin");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("photo");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("pseudo");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Pseudo")
                        .IsUnique();

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dca01717-e66d-4aaf-9d66-e4e32847b4b9"),
                            AcceptFood = false,
                            AcceptMusic = false,
                            AcceptPet = false,
                            AcceptSmallTalk = false,
                            AcceptSmoker = false,
                            Birthday = new DateTime(2024, 3, 12, 11, 2, 35, 171, DateTimeKind.Local).AddTicks(8029),
                            CarDescription = "",
                            Email = "admin@envoituresimone.com",
                            FirstName = "Admin",
                            IsAdmin = true,
                            LastName = "Admin",
                            Password = "admin",
                            PhoneNumber = "0102030405",
                            Photo = "https://thispersondoesnotexist.com/",
                            Pseudo = "admin"
                        },
                        new
                        {
                            Id = new Guid("8b2d4c69-f3d5-4d00-b02b-103bd26dd550"),
                            AcceptFood = false,
                            AcceptMusic = false,
                            AcceptPet = false,
                            AcceptSmallTalk = false,
                            AcceptSmoker = false,
                            Birthday = new DateTime(1998, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Daewoo",
                            Email = "naldren0@webeden.co.uk",
                            FirstName = "Amye",
                            IsAdmin = false,
                            LastName = "Colchett",
                            Password = "aB0.oB?iBy\\",
                            PhoneNumber = "0337862430",
                            Photo = "https://thispersondoesnotexist.com/",
                            Pseudo = "acolchett0"
                        },
                        new
                        {
                            Id = new Guid("b897d47e-7b3b-4dc0-a028-05d8e2c69659"),
                            AcceptFood = false,
                            AcceptMusic = false,
                            AcceptPet = false,
                            AcceptSmallTalk = false,
                            AcceptSmoker = false,
                            Birthday = new DateTime(1974, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Lexus",
                            Email = "ddroogan1@thetimes.co.uk",
                            FirstName = "Nap",
                            IsAdmin = false,
                            LastName = "Droogan",
                            Password = "tH0)I/Mt<xZwz2",
                            PhoneNumber = "0322458382",
                            Photo = "https://thispersondoesnotexist.com/",
                            Pseudo = "ddroogan1"
                        },
                        new
                        {
                            Id = new Guid("2c08f978-5efd-4471-b487-6df11f5ebd37"),
                            AcceptFood = false,
                            AcceptMusic = false,
                            AcceptPet = false,
                            AcceptSmallTalk = false,
                            AcceptSmoker = false,
                            Birthday = new DateTime(1988, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Jeep",
                            Email = "kpedwell2@icq.com",
                            FirstName = "Kordula",
                            IsAdmin = false,
                            LastName = "Pedwell",
                            Password = "pH3+&{WpvdT",
                            PhoneNumber = "0903434966",
                            Photo = "https://thispersondoesnotexist.com/",
                            Pseudo = "kpedwell2"
                        },
                        new
                        {
                            Id = new Guid("485e4e29-6217-415c-b438-3d4f114f24d6"),
                            AcceptFood = false,
                            AcceptMusic = false,
                            AcceptPet = false,
                            AcceptSmallTalk = false,
                            AcceptSmoker = false,
                            Birthday = new DateTime(1984, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "Austin",
                            Email = "lhair3@wikipedia.org",
                            FirstName = "Lindsey",
                            IsAdmin = false,
                            LastName = "Hair",
                            Password = "eE0'6STA~9O#Suj{",
                            PhoneNumber = "0162842195",
                            Photo = "https://thispersondoesnotexist.com/",
                            Pseudo = "lhair3"
                        },
                        new
                        {
                            Id = new Guid("24c952e2-dd86-4ca5-9308-771f2ab597fd"),
                            AcceptFood = false,
                            AcceptMusic = false,
                            AcceptPet = false,
                            AcceptSmallTalk = false,
                            AcceptSmoker = false,
                            Birthday = new DateTime(1997, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarDescription = "BMW",
                            Email = "cgrigorkin4@theatlantic.com",
                            FirstName = "Carlota",
                            IsAdmin = false,
                            LastName = "Grigorkin",
                            Password = "tZ9\\4s(DQvnvE",
                            PhoneNumber = "0494223557",
                            Photo = "https://thispersondoesnotexist.com/",
                            Pseudo = "cgrigorkin4"
                        });
                });

            modelBuilder.Entity("EVS.Core.Models.Feedback", b =>
                {
                    b.HasOne("EVS.Core.Models.Ride", "Ride")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVS.Core.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVS.Core.Models.Reservation", b =>
                {
                    b.HasOne("EVS.Core.Models.Ride", "Ride")
                        .WithMany("Reservations")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVS.Core.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVS.Core.Models.Ride", b =>
                {
                    b.HasOne("EVS.Core.Models.User", "User")
                        .WithMany("Rides")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVS.Core.Models.Ride", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("EVS.Core.Models.User", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Reservations");

                    b.Navigation("Rides");
                });
#pragma warning restore 612, 618
        }
    }
}
